### ISSUE TITLE
CW305 has not been added to the 4.0 api

### ISSUE THREAD

**Issue by FranzHeubach** [newaetech/chipwhisperer#121]
The CW305 target class needs to be changed to support the 4.0 api, as it currently does not. This is a reminder issue.

**Comment by rogerclarkmelbourne** [comment]
@FranzHeubach 

I was going to report that the CW305 script doesn't run
```

/software/chipwhisperer/capture/targets/CW305.py", line 31, in <module>
    from _base import TargetTemplate
ImportError: No module named _base
```

I need to write a script to connect to a USB device to send the data and I hoped to use it as a base/example. But it doesn't run

I guess I'll have to switch base to the 3.2.0 tag version using git
