### ISSUE TITLE
HAL for STM32F4 missing files

### ISSUE THREAD

**Issue by guilllaumeB** [newaetech/chipwhisperer#122]
Files stm32f4xx_hal_cryp* seem to be missing in your repo

**Comment by colinoflynn** [comment]
Possible it's only in the 'develop' branch (see https://github.com/newaetech/chipwhisperer/tree/develop/hardware/victims/firmware/hal/stm32f4).

**Comment by colinoflynn** [comment]
Closing as it sounds like this worked.
