### ISSUE TITLE
wiki: OSX installation, pyside

### ISSUE THREAD

**Issue by BenGardiner** [newaetech/chipwhisperer#123]
`brew install pyside` didn't work here. no such package, with homebrew `Homebrew/homebrew-core (git revision 7a58e8; last commit 2018-03-21)`

using pip (as documented at pyside docs http://pyside.readthedocs.io/en/latest/installing/macosx.html) did. i.e. `pip install -U PySide`

**Comment by cwiesnerNewAE** [comment]
Hi Ben, 

Thanks for reporting this issue. I've just updated the installation guide on the wiki to include this pip command.
