### ISSUE TITLE
Support FPGA Programming of Targets

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#124]
There is already code to download FPGA bitstreams. Would be nice to route that out the target, so can load the Spartan 6 LX9 target bitstream.

**Comment by rogerclarkmelbourne** [comment]
Just to add a little to this.

The Wiki pages for

> Building ISE Projects using MakeISE

and

> Building FPGA Partial Reconfig Files

Have not been written yet.

I've done a search on MakeISE but I don't get any useful results.

I presume that the Xilix ISE Design Suite is needed e.g.

https://www.xilinx.com/products/design-tools/ise-design-suite.html

But perhaps there is a smaller / cross platform alternative (Windows installer is almost 7Gb!)

**Comment by colinoflynn** [comment]
Did this get tested on HW?

**Comment by alex-dewar** [comment]
Closing as I believe this is covered by https://github.com/newaetech/chipwhisperer/issues/125
