### ISSUE TITLE
VM 4.0.1: Setup Issues

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#134]
Minor changes needed on VM:
1) Set default text editor inside ChipWhisperer to /usr/bin/geany (check for both analyzer & capture, should be shared IIRC).
2) Disable time-out that automatically puts lock screen up (or add much longer time-out)
3) Add README.txt to desktop with cwuser/cwpassword
4) Install following:
  a) pip install matplotlib
  b) apt-get install python-tk

**Comment by adamws** [comment]
are virtual environments prepared by hand? I suggest to start using [Vagrant](https://www.vagrantup.com/intro/index.html), it would make things a lot easier. I have some experience with it, so I could start preparing it if you are interested. 

Alternatively, Docker could be used but it would work only on linux machines (windows version does not support USB pass through). Also GUI would be a problem - although it works nice with jupyter and for release 5 it should included as alternative anyway.
