### ISSUE TITLE
Capturing seems to return wrong # of items sometimes

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#135]
When performing a capture, sometimes wrong number of traces saved. Noticably when doing captures for RSA demo which involve capturing several segments with 2 traces only. Looking in trace manager shows segments with 1, 2, or 3 traces.

**Comment by alex-dewar** [comment]
Segments are mostly in the background now, should test to verify this still isn't an issue

**Comment by alex-dewar** [comment]
I've added a unit test for projects with short segments lengths (currently just of length 2). There appears to be no issues accessing anything here, so closing.
