### ISSUE TITLE
Running scope.dis() then scope.con() disconnects waveform view

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#138]
If you run scope.dis() and then scope.con(), the waveform view does't update.

The work-around is to go to Results tab, select "None", then select "OpenADC/..." as the input source. 

The actual bug must be related to a signal is getting disconnected, and not reconnected properly. Note that if you create a NEW scope object (such as by calling the cwlite_connect script), you don't see this problem. So it's only when the old object is kept around and dis/con is called on it.

**Comment by alex-dewar** [comment]
GUI only issue, so closing
