### ISSUE TITLE
Multiple Programmers/Tools added

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#139]
It seems the 'Tools' (XMEGA programmer, STM programmer, etc) are sometimes duplicated. Assume related to multiple scope objects being created when you disconnect/reconnect. Should somehow make this less insane.

**Comment by FranzHeubach** [comment]
Did some research:
Every time a new scope object is added new menu items are added to the parameter list in the background as menu items. There is no easy way to tell which instance of the scope created which menu item. So there is no good way to refresh these every time without deleting the ones of the currently active scope. I am not saying it is not possible to fix but I did not see any non-insane way. Fixing this issue will require a rethinking of the way parts of the backend of chipwhisperer function.
