### ISSUE TITLE
git clone does a checkout of the develop branch

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#140]
Hello,

When performing a normal checkout of CW from git the default branch that is checked out is the develop branch. I would like to know if this is intentional.

Secondly following the git install tutorial some steps are missing.
Between the clone and the checkout of the branch you need to add cd chipwhisperer.

https://wiki.newae.com/Installing_ChipWhisperer#Installing_ChipWhisperer_from_Git
```
git clone https://github.com/newaetech/chipwhisperer.git
git checkout develop
cd chipwhisperer/software
python setup.py develop --user
```

Alternative is to do :
git clone https://github.com/newaetech/chipwhisperer.git -b develop

Or (to also checkout the openadc modules)

git clone https://github.com/newaetech/chipwhisperer.git -b develop --recurse-submodules 
``
why@login:~/tmp$ git clone https://github.com/newaetech/chipwhisperer.git -b develop --recurse-submodules  
Cloning into 'chipwhisperer'...
remote: Counting objects: 28049, done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 28049 (delta 67), reused 57 (delta 33), pack-reused 27926
Receiving objects: 100% (28049/28049), 85.78 MiB | 618.00 KiB/s, done.
Resolving deltas: 100% (19422/19422), done.
Submodule 'hardware/victims/firmware/crypto/secAES-ATmega8515' (https://github.com/jmichelp/secAES-ATmega8515.git) registered for path 'hardware/victims/firmware/crypto/secAES-ATmega8515'
Submodule 'openadc' (git://git.assembla.com/openadc.git) registered for path 'openadc'
Cloning into '/home/why/tmp/chipwhisperer/hardware/victims/firmware/crypto/secAES-ATmega8515'...
remote: Counting objects: 92, done.        
remote: Total 92 (delta 0), reused 0 (delta 0), pack-reused 92        
Cloning into '/home/why/tmp/chipwhisperer/openadc'...
remote: Counting objects: 2388, done.        
remote: Compressing objects: 100% (973/973), done.        
remote: Total 2388 (delta 1290), reused 2388 (delta 1290)        
Receiving objects: 100% (2388/2388), 10.62 MiB | 522.00 KiB/s, done.
Resolving deltas: 100% (1290/1290), done.
Submodule path 'hardware/victims/firmware/crypto/secAES-ATmega8515': checked out '7ada843c5bb0bb49c7f2bf5db72f9969e4091ba2'
Submodule path 'openadc': checked out 'ffa1eb159e160654d06da1cd89058e6e6a2c1158'
```

**Comment by FranzHeubach** [comment]
I have made the changes, thanks!
