### ISSUE TITLE
Tutorial B1 and B2 missing clock setup

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#144]
The B1 and B2 tutorial are missing the clock setup (found in setup_cwlite_xmega_aes.py).

Therefore the xmega does not respond to commands

**Comment by FranzHeubach** [comment]
I might be missing what you mean but in the tutorial it states you should run the setup_cwlite_xmega.py script, this sets up the clock and allows communication. Could you please clarify?

**Comment by x8-999-github** [comment]
you are correct
