### ISSUE TITLE
Python console only accepts a single line of input

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#145]
Thepyython console only accepts a single line of input. this is ratter confusing (see video)

[2018-05-08 10-19-00.zip](https://github.com/newaetech/chipwhisperer/files/1982959/2018-05-08.10-19-00.zip)

![selection_026](https://user-images.githubusercontent.com/22741063/39746105-a531a6d8-52a9-11e8-8529-5819f0ec18c2.png)

**Comment by FranzHeubach** [comment]
I will take a look at this and see if there is a quick fix to make this more intuitive. Thanks for raising an issue!

**Comment by FranzHeubach** [comment]
I found a quick fix, I just pushed it to develop branch. It now accepts multiple pasted lines. It also removes empty lines to keep the text display from looking chaotic. Thanks for the suggestion!
