### ISSUE TITLE
basic-passwdcheck.c faulty delay_200_ms

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#146]
Hi,

in the B3-1 Tutorial the following code can be found
```
static void delay_200_ms()
{
  for (volatile unsigned int i=0; i < 100000; i++ ){
    ;
  }
}
```
unsigned int on the xmega target are "only" two bytes hence a max delay of 65535 is the best achievable for now.  100000 results in the system never passing by the delay_200_ms code.

**Comment by x8-999-github** [comment]
```
static void delay_200_ms()
{
  for (volatile unsigned int i=0; i < 0xffff; i++ ){
    ;
  }
}
```

Gives a decent result (on xmega ad 7Mhz)

**Comment by FranzHeubach** [comment]
Thanks for the heads up, I can change that today.

**Comment by FranzHeubach** [comment]
The fix was just pushed to develop branch.
