### ISSUE TITLE
B3-1 Password_Bypass password does not match source code

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#147]
https://wiki.newae.com/Tutorial_B3-1_Timing_Analysis_with_Power_for_Password_Bypass

The screen shot in steps 11 shows the  wont passord (addional p)

**Comment by FranzHeubach** [comment]
Thank you! I took a look at the screen shot in step eleven (could only find one step 11). The serial message sent to target is highlighted in blue and is 'h0px3'. I am pretty sure this is the password in the source code. Let me know if I am missing something.

**Comment by x8-999-github** [comment]
There is a "t" in the screenshot . it is not blue but.. it is there 

![selection_027](https://user-images.githubusercontent.com/22741063/39763098-8f5473bc-52dc-11e8-83ba-c6cebab8c518.png)

**Comment by FranzHeubach** [comment]
fixed
