### ISSUE TITLE
B3-I tutorial last step

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#152]
I "almost" completed the tutorial but there is one problem remaining for me. Knowing when to stop 
To makes things easy it would be nice if there was some sort of way to detect the password was guessed correctly. The obvious way of doing this would be to check the serial output.. but this looks non trivial.

It is possible to do this?

**Comment by FranzHeubach** [comment]
target.readOutput() is the higher level function, you can also use target.ser.read(64, timeout=500), where 64 is the length of the data you would like to read. The target.readOutput function uses target.ser.read function within but deals with checking it is the expected length. Let me know if this helps.
