### ISSUE TITLE
Improve unconnected scope/target error messages

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#159]
Should possibly catch unconnected scope (scope = None) and see if better way to report error. Not clear yet if this can be done "cleanly", as don't want to introduce hacks/catch-all exceptions. If cannot be improved perhaps just document this...

**Comment by FranzHeubach** [comment]
Fixed with commit https://github.com/newaetech/chipwhisperer/commit/8a710a27fba1a9067130948edc8c1ddde90db2ab
