### ISSUE TITLE
Introduction_to_Glitch_Attacks

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#172]
https://wiki.newae.com/Tutorial_A2_Introduction_to_Glitch_Attacks_(including_Glitch_Explorer)

Setting up Glitch Example talks about editing the Makefile to set the target but the "modern" way of doing it is to create a Makefile.platform with the target

**Comment by alex-dewar** [comment]
Should be fixed up now. Thanks for the report.
