### ISSUE TITLE
Problems encountered in the raspberry pi Vcc Glitching experiment？

### ISSUE THREAD

**Issue by sikongsima** [newaetech/chipwhisperer#175]
Hi：
I have a problems in the raspberry pi Glitching experiment，my hardware model **raspberry pi 3 model b V1.2**, The IC is BCM2837，Chipwhisperer is ChipWhisperer-Lite（**CW1173**）,I follow the instructions from wiki，then solder a wire onto the VCC side of a decoupling capacitor, such as C67，But it doesn't work，What may be the reason？Thank you very much！！！
![_20180801172149](https://user-images.githubusercontent.com/30138974/43513607-c8af2fdc-95b0-11e8-9996-58549baa1919.png)
![_20180801172211](https://user-images.githubusercontent.com/30138974/43513613-ca00ede4-95b0-11e8-9a66-a351fc6c091c.png)
![_20180801173300](https://user-images.githubusercontent.com/30138974/43513669-f4ef9b9a-95b0-11e8-819d-1f9f35b96553.jpg)
![_20180801173340](https://user-images.githubusercontent.com/30138974/43513709-0b328840-95b1-11e8-8541-099a5c63b61a.png)

**Comment by sikongsima** [comment]
The CPU frequency is 1.2GHZ，I've tried a lot of frequency and  repeat settings

**Comment by sikongsima** [comment]
@x8-999-github  I observed glitch with an oscilloscope，the glithc width and offset tried many settings.

**Comment by alex-dewar** [comment]
Hi,

I'll be closing this issue soon as there's been no update in quite a while.
