### ISSUE TITLE
Annoying progress bar when warping traces

### ISSUE THREAD

**Issue by prestegaard** [newaetech/chipwhisperer#178]
When applying e.g. DTW on a trace set through the Analzer software an annoying progress bar spawns in front of the screen where the mouse pointer is active for every trace aligned. 
It would be nice to let this info be in the background somehow. 
![annying_progress_bar](https://user-images.githubusercontent.com/16774949/44029696-7baa7488-9efe-11e8-8d9e-45847a2f2e88.PNG)

**Comment by alex-dewar** [comment]
New CW5 release with Jupyter notebook interface has removed progress bar (along with GUI), so closing this issue.
