### ISSUE TITLE
API handbook

### ISSUE THREAD

**Issue by backahasten** [newaetech/chipwhisperer#179]
Where is the API manual for developing chipwhisperer Python scripts, and I want to try my own algorithms or add new device drivers

**Comment by backahasten** [comment]
I have find it in chipwhisperer-master/doc/sphinx it can be make as pdf,epub,html and so on.

**Comment by colinoflynn** [comment]
FYI - that is about to majorly change! There is an updated Python 3 version in the works that will have more/better API documentation, but break a few things in the process...
