### ISSUE TITLE
CW5: STM32F programmer broken

### ISSUE THREAD

**Issue by Marandil** [newaetech/chipwhisperer#181]
STM32F programmer is currently broken for Python 3 and returns:
```chipwhisperer.hardware.naeusb.programmer_stm32fserial.CmdException: NACK 0x31 address failed```
on any `program` call, even for simple examples and example scripts.

The problem is caused by address being incorrectly converted to string in _encode_addr function. If anything, it should be converted to `bytes` object instead.

The following diff solved the problem in my case:

```
--- a/software/chipwhisperer/hardware/naeusb/programmer_stm32fserial.py
+++ b/software/chipwhisperer/hardware/naeusb/programmer_stm32fserial.py
@@ -369,7 +369,7 @@ class STM32FSerial(object):
         baddr = bytearray(struct.pack(">L", addr))
         crc = reduce(lambda x, y: x ^ y, baddr)
         baddr.append(crc)
-        return str(baddr)
+        return bytes(baddr)

     def cmdReadMemory(self, addr, lng):
         assert (0 < lng <= 256)
```

**Comment by colinoflynn** [comment]
Thanks for report - haven't tried STM on CW5 so good to know it's an easy fix! Will push that asap
