### ISSUE TITLE
CWCapture Scope Settings tab blank with Nano

### ISSUE THREAD

**Issue by alex-dewar** [newaetech/chipwhisperer#186]
When using CWCapture and the CWNano, the _Scope Settings_ tab is always blank, preventing settings from being changed in the GUI. Settings can still be changed in the _Python Console_.

**Comment by colinoflynn** [comment]
Oh yeah, I wasn't even bothering adding it to CW4, as the parameter-tree stuff is dropped in CW5. Possibly this is "by design" I can claim then...
