### ISSUE TITLE
[cw5dev] avoid spaces in notebook filenames

### ISSUE THREAD

**Issue by doegox** [newaetech/chipwhisperer#187]
Current notebook pages have spaces in their name.
This prevents cross-referencing them in Markdown from a notebook to another one with the syntax `[another tutorial](Tutorial A0 (blah).ipynb)`.
Please replace spaces by `-` or `_`.

**Comment by colinoflynn** [comment]
Good catch! Will rename... had planned on changing the naming scheme a bit too (since 'basic' vs 'advanced' didn't make sense all the time anyway). So would be a good time to do so.

**Comment by adamws** [comment]
One additional note from my side. If notebooks are meant to replace tutorials, you should commit them with outputs computed. Then you could even use service like [nbviewer](https://nbviewer.jupyter.org/) to share them outside github like this [book](https://nbviewer.jupyter.org/github/unpingco/Python-for-Signal-Processing/tree/master/) for example.

**Comment by alex-dewar** [comment]
Should be fixed by f360b421b44a28d61f546cc517579e3d4c9f7de5. Thanks for the suggestion regarding the outputs. I've moved that to a separate issue
