### ISSUE TITLE
Stability issues on idle system (cw5dev)

### ISSUE THREAD

**Issue by Mrkvak** [newaetech/chipwhisperer#203]
I've noticed CWLite board when using software from cw5dev branch is not exactly stable: STM/XMEGA programming times out almost always fails, scope in examples does not trigger when it's supposed to, etc...  

Then I've noticed everything works when system is under heavy load (compiling something, etc...), example is here: https://pastebin.com/msWsVnZX
Then I've noticed everything works after I add a sleep() to start of txrx method in newaeusb.py. Even the smallest sleep interval seems to help - I'm currently using time.sleep(0.00000000001).

I know there's a big chance this is not a chipwhisperer issue at all, but I think it is worth some investigation. I'm running Gentoo, kernel 4.20.0-gentoo, I'll try it with another system on same hardware soon.

**Comment by colinoflynn** [comment]
Thanks for the catch! We might need to tune this... so we *had* some delays in the code that we removed, as they killed performance on CW5 (compared to the previous CW3, we had 1/2 capture speeds). We'll add the delay in I think to help with that...

FWIW - the "best" solution is I think to enable an option to have a "system" serial port. We avoided that as it means you need to track COM or /dev/ttyUSBx numbers. But it eliminates all these hacky delays we had to add in...

**Comment by alex-dewar** [comment]
Closing this as I don't think we've run into this for quite a while
