### ISSUE TITLE
make fail when generating simpleserial on windows 7

### ISSUE THREAD

**Issue by edaho1** [newaetech/chipwhisperer#206]
Hi,
I am new to Chipwhisperer; I am running Chipwhisperer.v4.0.1 on Windows7. I was following the tutorial for the '[SimpleSerial](https://wiki.newae.com/Tutorial_B1_Building_a_SimpleSerial_Project)' however, when I reached the **make** portion under 'Building the Basic Example', I received the following error message:

make PLATFORM=CW303
rm -f -- simpleserial-base-CW303.hex
process_begin: CreateProcess (NULL, rm -f -- simple-serial-base.hex, ....) failed
make (e=2): The system cannot find the file specified
makeL *** [.././Makefile.inx:513: clean_objs] Error 2

![error_when_running_make](https://user-images.githubusercontent.com/22598771/53294372-8a459380-37b3-11e9-8db1-69ff9551bfbc.PNG)

**Comment by rob0tsunny** [comment]
could you edit makefile and add '-' in front of this command: "rm -f -- simpleserial-base-CW303.hex" ?

**Comment by edaho1** [comment]
Thank you
