### ISSUE TITLE
No CWNANO Atmel ARM firmware or source for programming and other small issues

### ISSUE THREAD

**Issue by jogolden** [newaetech/chipwhisperer#217]
I have erased my CW1101-04 on purpose thinking that a firmware or even source code would be available. I guess I made a mistake! I have searched throughout this repository, mostly in `hardware/capture` and I could not find any firmware blobs or source! :( Even if you dont release the firmware source code right now, could someone send me a proper firmware blob that I can flash with Bossa? Any help would be much appreciated! It just has the dim lit green and red USB/ERROR lights and shows up as "Atmel Corp. at91sam SAMBA bootloader" which makes sense and should happen because I erased it.

There are also issues with the CWNANO build system, I tried to build the `simpleserial-aes` using `make PLATFORM="CWNANO"` and it will spit out an error `.././crypto/avrcryptolib//aes/aes_enc.c:34:26 fatal error: avr/pgmspace.h: No such file or directory`. If you try to fix this with `CFLAGS="-I /usr/lib/avr/include" make PLATFORM="CWNANO"` it still fails due to issues with pgmspace.h's assembly definitions.

Also there ought to be support for when you instantiate a `chipwhisperer.scope` object it will recognize the CWNANO's USB ID codes and you wont have to use `chipwhisperer.scope(chipwhisperer.scopes.CWNano)` but I suppose this is not that important. The firmware for the Atmel chip is the most important.

Other than the above issues... the CWNANO is really fun and looks to be a really promising beginner device! :+1:

**Comment by colinoflynn** [comment]
Hello - all the FW update stuff wasn't pushed in for the nano Ithink, it's a TODO on our side still! I forgot to include that however... the quick fix is to use the attached firmware file (unzip it). The following piece of code "should" program it, in case other methods aren't working.

```
def program_sam3u(comport, fname):
    # Program a "virgin" ChipWhisperer with the firmware
    from chipwhisperer.hardware.naeusb.bootloader_sam3u import Samba
    try:
        sam = Samba()
        sam.con(comport)
        sam.erase()
        data = open(fname, 'rb').read()
        sam.write(data)
        ret = sam.verify(data)
        if ret:
            sam.flash.setBootFlash(True)
        sam.ser.close()
        return ret
    except:
        return False

program_sam3u("com22", r'cwnano-firmware.bin')
```

[cwnano-firmware.zip](https://github.com/newaetech/chipwhisperer/files/3343047/cwnano-firmware.zip)

On the second issue - you need to specify *not* to use the AVR crypto libs. It should work with also including CRYPTO_TARGET = TINYAES128C)

A lot of this is being smoothed out in the current release - basically all the 'various flags' are being consolidated such that it's more clear what is supported on various platforms.

Hopefully that solves what you need for now! Keep an eye out for the full CWNANO support in the next release (much of this is now in git on the 'cw5dev' branch anyway).
