### ISSUE TITLE
SW: Can't program XMEGA/AVR without GUI

### ISSUE THREAD

**Issue by gregdeon** [newaetech/chipwhisperer#22]
The XMEGA programmer GUI has some of the logic for programming the XMEGA targets, and it's impossible to make a programmer object without the GUI. It should be much easier to program an XMEGA from the command line.

**Comment by adamws** [comment]
Hi, I needed to automate target flashing so I written [this.](https://gist.github.com/adamws/83220bdca9c53e051331c73f80cf3b16) Maybe you will find it useful. Tested on CW lite.

**Comment by alex-dewar** [comment]
Fixed in https://github.com/newaetech/chipwhisperer/blob/3fa31419ca19cac05d84ed6792c09a9bc73da08a/software/chipwhisperer/capture/api/programmers.py
