### ISSUE TITLE
Update Pro only features for CW5

### ISSUE THREAD

**Issue by alex-dewar** [newaetech/chipwhisperer#220]
Currently working on:

* ~Stream mode~
* ~SAD Trigger~
* ~Decode Trigger~

**Comment by Wmyers559** [comment]
What would need to be done to take care of this? I'm willing to help if I am able to.

**Comment by alex-dewar** [comment]
Currently, not much work has been done getting the pro specific features (SAD trigger, stream mode, and decode trigger) ready for CW5. The current plan is to get the interface cleaned up a bit, get it documented, then write some notebooks about how to use them.

If you do want to work on it, the decode trigger (cwhardware/ChipWhispererDecodeTrigger.py) is probably the best place to start, since that looks to be the least reliant on the GUI. Even just removing param stuff and verifying everything still works would be helpful.

**Comment by alex-dewar** [comment]
The Pro's stream mode should now work. Any long capture won't display well using any browser based graphing utility, so this mode probably won't be much use until the Lite GUI gets implemented.

**Comment by alex-dewar** [comment]
The Pro's SAD now works. The `scope.trigger.module` can now be used to set different modules if the Pro is connected, but remains readonly for the Lite. The SAD trigger module now appears when printing the scope object.

**Comment by alex-dewar** [comment]
Decode trigger now works as well.
