### ISSUE TITLE
Minor inconsistency in Fault_2-Introduction_to_Vcc_Glitch_Attacks.ipynb tutorial

### ISSUE THREAD

**Issue by AsFaBw** [newaetech/chipwhisperer#235]
There is a minor inconsistency in the documentation. It states:

> Instead of setting the clock source for the target to be the glitch module, we instead set the low power MOSFET's input to be the glitch module by setting scope.io.glitch_lp to True. The ChipWhisperer-Lite also has a high power MOSFET, but we won't be using that in this tutorial.

Within the code it is in contrast:
```
 def glitch_on(scope):
        scope.io.glitch_lp = False
        scope.io.glitch_hp = True
    def glitch_off(scope):
        scope.gio.glitch_hp = False

```

**Comment by alex-dewar** [comment]
Should be fixed now
