### ISSUE TITLE
Small issue in TVLA ktp generator

### ISSUE THREAD

**Issue by Wmyers559** [newaetech/chipwhisperer#240]
Hello,

I was going through the TVLA KTP generator after some unusual behavior, and I noticed that the decrement 
```
if self.num_group1 > 0:
    self.num_group1 -= 1
```
was removed in 98cda3ff. This causes the output of this generator to be biased towards emitting plaintexts from group one (chained AES) vs. group two (fixed plaintext).

I have a patch that fixes this already--want me to throw it in a merge request, or do you want to take care of it yourself?

Thanks!

**Comment by alex-dewar** [comment]
Good catch! A patch would be much appreciated.

Alex
