### ISSUE TITLE
Cannot use a faster external clock with STM32F3 target

### ISSUE THREAD

**Issue by KaneX** [newaetech/chipwhisperer#244]
Hello, I am trying to use the STM32F3 target with a 25MHz external clock, but I am not sure how to configure the compiling files. 

I have tried changing:
F_CPU in Makefile.hal;
Return values in HAL_RCC_GetSysClockFreq() and HAL_RCC_GetPCLK1Freq() in stm32f3_hal_lowlevel.c;
HSE_VALUE in stm32f3_hal_lowlevel.h,
but none of these seems to work.

Could anyone tell me how to configure the files? Or does the STM32F3 target support a faster external clock?

**Comment by alex-dewar** [comment]
This should be fixed by 9ca358d2a1da4f3cf11d5808bc851f4147b647c6. The correct function to change was HAL_RCC_GetPCLK2Freq().
