### ISSUE TITLE
Schematic for the 32-bit ChipWhisperer-Lite?

### ISSUE THREAD

**Issue by adamheinrich** [newaetech/chipwhisperer#246]
Hello, could you please release schematic for the 32-bit CW Lite (or at least its STM32 victim board)?

The repository only includes [schematic](https://github.com/newaetech/chipwhisperer/blob/2297218349bfc6ae455bb54c46cd1f55e5b9d162/hardware/capture/chipwhisperer-lite/pcb/cw-lite-main.pdf) with the XMEGA victim.

Thank you!

**Comment by colinoflynn** [comment]
Fixed - see https://github.com/newaetech/chipwhisperer/blob/develop/hardware/capture/chipwhisperer-lite-32bit/cw-lite-arm-main.pdf

**Comment by colinoflynn** [comment]
PS - the only diff is the target section (the one page)

**Comment by adamheinrich** [comment]
Wow, that was fast:) Thank you.
