### ISSUE TITLE
SW: CWCapture UI is slow for long captures

### ISSUE THREAD

**Issue by gregdeon** [newaetech/chipwhisperer#25]
Some people are reporting that the ChipWhisperer GUI gets extremely slow when capturing thousands of traces. Increasing the number of trace sets doesn't seem to help. See [this forum thread](https://www.newae.com/forum/viewtopic.php?f=7&t=217) I haven't been able to reproduce this on my end.

**Comment by alex-dewar** [comment]
No UI anymore, so closing
