### ISSUE TITLE
SAM_CS2 Not connected

### ISSUE THREAD

**Issue by naasik12** [newaetech/chipwhisperer#250]
Hi I was reviewing the Schematics. Is there missing pins or connections from the schematics?

Kind Regards

**Comment by colinoflynn** [comment]
Not sure what you mean? Is this for CW-Lite? There hasn't been updates in a long time, those schematics are "golden" in that PCB etc is done for that.

**Comment by naasik12** [comment]
Hi Colin
SAM_CS2 has no target point.
Thanks for replying.

![Uploading Untitled.png…]()

**Comment by naasik12** [comment]
![Untitled](https://user-images.githubusercontent.com/40466104/71589165-877ea200-2b2c-11ea-8478-9e30cd0281e8.jpg)

**Comment by colinoflynn** [comment]
Ah gotcha! Yeah that goes nowhere, I think it was a possible usage, but it's a N/C in the end.

Anything with a connection will tell you the sheet & location on the sheet (i.e., SAM_CS1/7.5H means Sheet 7, Location 5-H). Although I think in my case I didn't actually use the schematic sheet that had XY marking, so they are useless (the marking of location is done automatically)
