### ISSUE TITLE
Update the Virtual Box extension pack link in the documentation

### ISSUE THREAD

**Issue by axlan** [newaetech/chipwhisperer#253]
The link in https://github.com/newaetech/chipwhisperer/blob/master/docs/installing.rst currently points to https://download.virtualbox.org/virtualbox/6.0.6/Oracle_VM_VirtualBox_Extension_Pack-6.0.6.vbox-extpack which is not compatible with the newest Virtual Box (v6.1.2). However, the link on the downloads page referenced right above it has a link to the newest extension pack. Since trying to install the old pack gives a somewhat cryptic error, the documentation should probably take out the direct link, and just mention that the pack is on the downloads page as well.

**Comment by alex-dewar** [comment]
Thanks for the heads up. Instead of directly linking, we now just tell the user to install it from the same page as they installed virtualbox from. This should hopefully prevent version mismatch in the future as well.
