### ISSUE TITLE
cw.capture_trace may be oversimplified

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#257]
cw.capture_trace doesn't work on "old" 1.0 protocol (w/o ACKs). The LX9 target for example still uses that protocol due to implementing it in FPGA.

You can't override that, as the functions don't respect the 1.0/1.1 version (or try to auto-detect). Probably need to add slightly more intelligence back, or think about if we still want autodetect.

Flagging it for now to not forget.

**Comment by alex-dewar** [comment]
I've added an ack argument to capture_trace() that allows for wait_for_ack() to be bypassed. We could do autodetect in the future, but I wanted to avoid changing the API
