### ISSUE TITLE
IO Connection table for CW308T-RV-beta

### ISSUE THREAD

**Issue by tonkapango** [newaetech/chipwhisperer#263]
Is it possible, like with the other targets, to get schematics of which pin on the FE301-G002 UFO target corresponds to which CW308 pin.  specifically, i am looking at the trigger.  thanks.

**Comment by colinoflynn** [comment]
Schematics now updated at https://github.com/newaetech/chipwhisperer-target-cw308t/tree/master/CW308T_FE310-G002 - note the major silkscreen bug for anyone else that lists the wrong connection for GPIO3!
