### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by JohnLoveMm** [newaetech/chipwhisperer#268]
I am newer of the chipwhisperer,and iI can not find a example of the package,I want somebody give some guide,thank you!

**Comment by alex-dewar** [comment]
Hi,

Most of our documentation on the software side is on our [readthedocs page](https://chipwhisperer.readthedocs.io/en/latest/index.html), including installation instructions and the API. The jupyter submodule also has jupyter notebook based tutorials, completed versions of which can be found on our readthedocs page: https://chipwhisperer.readthedocs.io/en/latest/tutorials.html.

We also have [forums](https://forum.newae.com), which is probably a better place to ask more general questions like this.

Alex

**Comment by colinoflynn** [comment]
I'm going to close this issue - but might actually pin a new "getting started" issue since the documentation is for now easy to miss some important links! If we can save people some time makes sense.

**Comment by JohnLoveMm** [comment]
I'm glad you answered my question,thank you very much.
