### ISSUE TITLE
Cannot switch from CW1200 to CWLite, hard to modify CW1200 FW Settings

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#27]
Currently the CW1200 and CWLite firmware is one object that gets switched depending if a CWLite or CW1200 is detected. This ends up being pretty clunkly and causes many bad things (TM), including trying to load the wrong firmware when switching tools.

Should have seperate objects, maybe seperate pull downs are thus required.

**Comment by gregdeon** [comment]
https://github.com/newaetech/chipwhisperer/commit/5d13de95d258a94d0def339ab1657d1e8bf19f65
