### ISSUE TITLE
SMA on CW1200 - Trigger In Disabled

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#270]
The FPGA code was changed to disable the trigger input it looks like. With the recent rebuild this actually got pushed out to people.

https://github.com/newaetech/chipwhisperer/blob/develop/hardware/common/hdl/reg_chipwhisperer.v#L257 looks to be offending line - but need to check as this was done some time ago.

**Comment by alex-dewar** [comment]
Tested this out on the latest commit, and AUX in definitely still works. The bitstream was built with that still commented out, so it could be referring to something else, or the actual code could be elsewhere.
