### ISSUE TITLE
running cw software in linux

### ISSUE THREAD

**Issue by mati335** [newaetech/chipwhisperer#278]
so sorry for the noob question but how do you run the analyzer and capture software without jupyter

**Comment by alex-dewar** [comment]
Almost exactly the same as within Jupyter, via the ChipWhisperer API, minus the Jupyter specific magics (like `%matplotlib notebook` and `%%bash` and the like).

If you're wondering about the old GUIs, those were removed with the ChipWhisperer 5 update.

**Comment by colinoflynn** [comment]
Also - the old GUIs were removed in part as they relied on PySide (not PySide2), which is Python2.7 only and it was non-trivial to port, so it's not a case of them just being somewhere hidden!

If you need the install directions, you can see them at https://chipwhisperer.readthedocs.io/en/latest/prerequisites.html#prerequisites-linux
