### ISSUE TITLE
Fix firmware file rebuild script

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#28]
As suggested by Thomas Jarosch: you could make a "smart" rebuild logic: Cache the sha256sum of the input files in an extra file. If they sha256sum of a file changes, regenerate the output file and update the cache.

**Comment by alex-dewar** [comment]
Make already has a system for this, so the build system could probably be changed to incorporate this (https://stackoverflow.com/questions/7815400/how-do-i-make-makefile-to-recompile-only-changed-files)

**Comment by alex-dewar** [comment]
Closing this, as I believe there's already a quickbuild system.
