### ISSUE TITLE
Missing files for simulation on SCA101 Lab 3_3

### ISSUE THREAD

**Issue by Rodrigojflima** [newaetech/chipwhisperer#288]
I have been trying to do all tutorials that I can get my hand on to learn (SCA) chispwhisperer software using the new jupyter notebook reality.
It happens that to run Lab3_3, the files with the tracedata and textindata are missing. I've searched and most likely running the Lab3_3 Generator would generate the files that I need. Is there any way to provide those please?

**Comment by alex-dewar** [comment]
Thanks for letting us know! They should be in the newest jupyter commit.

**Comment by Rodrigojflima** [comment]
Solved! I'm closing the issue now!
