### ISSUE TITLE
py2exe / Binary Distribution

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#29]
Have long thought of making a distribution using something like py2exe. So far I haven't done a lot of research into that, as are other options & also can do similar for macos. This issue is to track suggestions/notes:

Initial notes:

* Would be good to still be able to modify some underlying files possibly.
* Can install drivers at same time?

**Comment by alex-dewar** [comment]
Closed this as I don't think it makes sense to do a python only exe with Jupyter
