### ISSUE TITLE
SCA201 Missing Files for simulation

### ISSUE THREAD

**Issue by Rodrigojflima** [newaetech/chipwhisperer#290]
I was trying to do all the simulated tutorials on SCA201. Seems like there are still some missing trace files. I understand that it is still in development, but is there any chance we can get those files?

**Comment by alex-dewar** [comment]
Thanks for letting us know! I've added traces for the resync labs and 32-bit AES lab. The HW AES lab may follow some time in the future.

**Comment by Rodrigojflima** [comment]
Many thanks, should be enough for me!
Closing the issue now!

**Comment by Rodrigojflima** [comment]
It actually seems like there is no update yet on the master.

**Comment by alex-dewar** [comment]
Oh sorry, just hadn't updated the jupyter submodule link. It should be updated now

**Comment by Rodrigojflima** [comment]
It is, thank you!
Closing now.
