### ISSUE TITLE
Check for pyusb < 1.1.0

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#291]
With change to use libusb1, you get a horrible error on Windows if using pyusb < 1.1.0.

Should check if user is attemping to use too old a version, can get version with:

    import usb
    print(usb.__version__)

If only a Windows error we could add just a warning, or even only print the problem if there is an error on USB connect.

**Comment by alex-dewar** [comment]
There is this currently: https://github.com/newaetech/chipwhisperer/blob/develop/software/chipwhisperer/__init__.py#L27. Do we want to change it to throw an exception instead?

**Comment by alex-dewar** [comment]
Closing as we no longer use pyusb
