### ISSUE TITLE
missing "int i" in aes-independant.c MASKED_AES

### ISSUE THREAD

**Issue by aXnXlXe** [newaetech/chipwhisperer#296]
For MASKED_AES in `void aes_indep_enc_posttrigger(uint8_t * pt)` `int i` is missing.

**Comment by alex-dewar** [comment]
Thanks for the catch! Fixed by 71f24d0f11f9cf4866347faf6af38de52bf497fe

**Comment by alex-dewar** [comment]
Or rather d810caaee2e8b66b7d9d6b01ccd57ba93dacba17
