### ISSUE TITLE
No FW binary 0.23 for cw-lite

### ISSUE THREAD

**Issue by mprt** [newaetech/chipwhisperer#310]
Looks like in https://github.com/newaetech/chipwhisperer/commit/010987c9983afb80be3faba610a489253e2dbef5 you forgot to add the current FW binary (v0.23) for the CW-lite.

would be great if you could spare some 5 minutes and build it. 

Thanks!

**Comment by alex-dewar** [comment]
Thanks for the report! I believe I still have the correct binary in my repo uncommitted, so I'll get that pushed out asap.

**Comment by alex-dewar** [comment]
Should be up to date on the latest commit
