### ISSUE TITLE
SimpleSerial read not blocking

### ISSUE THREAD

**Issue by opcod3** [newaetech/chipwhisperer#331]
Using a CW1200, when attempting to read bytes from a SimpleSerial UART target in a blocking manner using ```target.read(18, 0)``` the read does not block and instead behaves as if the timeout were zero. This is does not match the code and the documentation.

**Comment by alex-dewar** [comment]
Thanks for the report! Fixed by 098b54a1c66f2d3308b8352f73220f37808609ae (I've also updated the docs)
