### ISSUE TITLE
Self-programming issue on CW303 XMEGA Target

### ISSUE THREAD

**Issue by fallazc** [newaetech/chipwhisperer#339]
I am trying to upload a program that uses the [XMEGA Self-programming example](https://www.microchip.com//wwwAppNotes/AppNotes.aspx?appnote=en591513) where some of the functions need to be located in bootloader section to be able to use the SPM instructions.

I defined in a .BOOT section at address 0x20000(should be the bootloader section of the ATXmega128D4-AU on the XMega target) which in the Makefile is defined as:

`LDFLAGS += -Wl,–section-start=.BOOT=0x20000`

Problem is, I keep getting the errors linked below.
![error trace](https://i.imgur.com/9Kyi9Dz.png "File")

Someone on the forum mentioned that it might be a an issue with the lock-bits / fuses but I am sure how these can be changed since they are not exposed by the [Xmega Programmer](https://github.com/newaetech/chipwhisperer/blob/88fb75f587f0d71e7cd1b228d8476a5646763f2d/software/chipwhisperer/capture/api/programmers.py#L209).

Any ideas how to get this working?

**Comment by fallazc** [comment]
Thanks for linkoing those, they have been quite helpful in trying to figure this out.

From what I gathered, it looks like I first have to `enablePDI(true)` but I don't know how to send the actual PDI commands from the instruction set(Table 2-1, page 4) or the NVM commands(Table 2-2, page 5) for that matter.

I am having trouble finding any reference to the command listed in the aforementioned tables, I also looked at [naeusb.py](https://github.com/newaetech/chipwhisperer/blob/9b6825b495f14f85aae8b11007c63c59a1654584/software/chipwhisperer/hardware/naeusb/naeusb.py) but couldn't find anything either.

Do you have any pointers or example of how to send the PDI? 

Thanks

**Comment by colinoflynn** [comment]
As a quick ref - the lower-level stuff happens on the microcontroller side at https://github.com/newaetech/chipwhisperer/blob/master/hardware/capture/chipwhisperer-lite/sam3u_fw/SAM3U_VendorExample/src/pdi/XPROGNewAE.c#L60 . Let me see if there is a sane way to do what you need as the older stuff gets a little messy...

**Comment by colinoflynn** [comment]
On current CW:
```
import chipwhisperer as cw
scope = cw.scope()
```

You can then access the xmega class with: `scope.scopetype.dev.xmega`

Which points to the [programmer_xmega.py](https://github.com/newaetech/chipwhisperer/blob/develop/software/chipwhisperer/hardware/naeusb/programmer_xmega.py) file.

So we could do:

```
xmega = scope.scopetype.dev.xmega
xmega.find()
xmega.close()
```

There is low-level commands mentioned, but those are the commands to our firmware. Luckily I think you can ignore that by referencing the fuse byte addresses, see for example: https://github.com/newaetech/chipwhisperer/blob/develop/software/chipwhisperer/hardware/naeusb/programmer_xmega.py#L77

```
xmega.find()
xmega.readMemory(0x8f0021, 1, "fuse1")
xmega.close()
```

This doesn't actually work for me - so I need to debug, but FYI we in theory had the commands in there. I don't know they've ever been tested...

**Comment by alex-dewar** [comment]
I believe the commands are only implemented for the AVR. I'd recommend adding a read/writeFuse() method to XMEGAPDI in https://github.com/newaetech/chipwhisperer/blob/develop/software/chipwhisperer/hardware/naeusb/programmer_xmega.py. Something along the lines of:

```python
def writeFuse(self, data):
    self.validate_mode()
    self._xmegaDoWrite(0x4C, data) #0x4c is writeFuse 
```

Plus probably a little validation. Reading the fuse byte should be similar.

I don't think you really need to do much beyond that - most of the code in the writeMemory method is for handling pages/words and large amounts of data.

Long term it would be good to add an interface in https://github.com/newaetech/chipwhisperer/blob/develop/software/chipwhisperer/capture/api/programmers.py, but accessing via `prog.xmegaprog.writeFuse()` works in the short term.

If you don't mind waiting a bit, I can quickly throw something together for you.

**Comment by fallazc** [comment]
I just want to unlock the usage of SPM instructions so at this point I would just be happy setting the lock bits to 0xFF.
I tried: 
`xmega.validate_mode()`
`xmega._xmegaDoWrite(cmd=0x08, data=[0xFF])`
It executes fine but that doesn't seem to actually change the lock bits because the target's bootloader section cannot be programmed.

**Comment by alex-dewar** [comment]
It turns out that lock bits can only be set higher, but not lower by the lock bit write command. Instead, a chip erase
should be done:

```python
xmega.erase("chip")
```

**Comment by fallazc** [comment]
I tried adding that just before the write but didn't make difference.
Looking at the manual it looks like the easiest way would be to implement this directly in [XMEGANVM](https://github.com/newaetech/chipwhisperer/blob/49260f902e2018c931d3ad08f15c8b42092649fc/hardware/capture/chipwhisperer-lite/sam3u_fw/SAM3U_VendorExample/src/pdi/XMEGANVM.c).
I could throw something together and start testing. The question now is how do I program the updated protocol to the capture board?

**Comment by alex-dewar** [comment]
Nevermind, I think what's missing are the erase/write bootloader commands. The bootloader section should be unlocked by default. Everything is implemented already on the capture board, `xmega.writeMemory()` just needs to be updated to use the bootloader commands if the memory is in the bootloader section (plus a bootloader erase command, I think).

**Comment by alex-dewar** [comment]
I've added a potentially working implementation for bootloader erase/programming. The bootloader section has to start at 0x00 and be a separate hex file due to how the writeMemory method works, functioning similar to eeprom. 

To erase bootloader memory:

```python
xmega.erase("bootloader")
```

To program:

```python
xmega.program("bootloader.hex", memtype="boot")
```

**Comment by fallazc** [comment]
Thanks for the update! 

Having separate hex files seems like a bit more maintenance work so I got around the programming issue by defining a unique value for the memory type.

If you look at [XPROGProtocol_WriteMemory](https://github.com/newaetech/chipwhisperer/blob/49260f902e2018c931d3ad08f15c8b42092649fc/hardware/capture/chipwhisperer-lite/sam3u_fw/SAM3U_VendorExample/src/pdi/XPROGNewAE.c#L225), whole flash programming is assumed by default. So passing a value such as 0 for memory type and with a properly linked hex file, functions will be stored where they belong.

Now the issue still remains the lock bits as even though the code is stored in the bootloader section it still cannot use the self-programming features.

**Comment by alex-dewar** [comment]
According to the datasheet, the xmega is completely unlocked by default and we don't set any lock bits, so I don't think lock bits are the issue. 

Looking at the PDI documentation I posted earlier, I don't think the normal flash commands work on the boot section of the flash as there are separate commands for writing the boot section.

**Comment by alex-dewar** [comment]
Closing this as lock bits are set to 0xFF upon chip erase, which is already implemented.
