### ISSUE TITLE
Empty Setup_Generic.ipynb file for Jupyter Notebook VM in BlackHat2021 Release

### ISSUE THREAD

**Issue by JeremyV2014** [newaetech/chipwhisperer#350]
I've encountered an issue trying to run the first step of _Section 1.2  ChipWhisperer Hardware Test_ in the _ChipWhisperer Setup Test_ jupyter notebook. I'm using the release version of the Jupyter Notebook VM for BlackHat 2021. I get this [output](https://github.com/newaetech/chipwhisperer/files/6909138/SetupCommandOutput.txt) when running the command.

I get the following error when I try to view _Setup_Generic.ipynb_ in Chrome:

![image](https://user-images.githubusercontent.com/9276415/127690065-253b4fd5-72b5-4003-815d-5c50e36d5be1.png)

Opening the file on the VM in nano shows that it is completely empty:

![image](https://user-images.githubusercontent.com/9276415/127690370-cfef057c-3815-4879-abd2-f0b5315bb8b2.png)

I tried re-downloading and extracting the VM and ran into the same issue. Can someone correct this?

**Comment by colinoflynn** [comment]
Hmm - sorry we ran into this & thought it was limited to a few people, it seems the file got zerod at some point.

If you run a cell with this it should work:

```
!git checkout Setup_Scripts/Setup_Generic.ipynb
```

Basically need to re-check-out that file and it seems to fix it.

**Comment by JeremyV2014** [comment]
@colinoflynn That fixed the issue for me. Thanks!

**Comment by alex-dewar** [comment]
Going to reopen this until the end of Black Hat so that people can find it a bit easier.
