### ISSUE TITLE
Improve CWNANO Target Support for different flash sizes

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#375]
Brought up by #374 .

The CW-NANO has at least two different target devices used in the production runs. They have different flash sizes - some have larger flash (32KB) some have smaller flash (16KB). The default linkerscript assumes the smaller in all cases, and it's not obvious if the "flash overflow" problem is true or not.

Need to:
- [ ] Improve documentation (rtfm.newae.com site & maybe RTD site)
- [ ] Investigate if we can auto-detect this in programming, and maybe change linkerscript to assume 32KB then detect it on programming.

**Comment by alex-dewar** [comment]
We now use 32k of flash for the Nano, but will warn the user if >16k is used and the device only has 16k of flash.
