### ISSUE TITLE
1-Conecting to Hardware

### ISSUE THREAD

**Issue by tkyhgs** [newaetech/chipwhisperer#377]
Building and Uploading Firmware part doesn't work well.
Please tell me  what should I do?

command↓
%%bash 
cd ../hardware/victims/firmware/simpleserial-base/
make PLATFORM= CRYPTO_TARGET='CWNANO'

message↓
SS_VER set to SS_VER_1_1
.././hal/Makefile.hal:234: *** Invalid or empty PLATFORM: . Known platforms: 
+-------------------------------------------------------+
| PLATFORM      | DESCRIPTION                           |
+=======================================================+
| AVR/XMEGA Targets (8-Bit RISC)                        |
+=======================================================+
+-------------------------------------------------------+
| CWLITEXMEGA   | CW-Lite XMEGA (Alias for CW303)       |
+-------------------------------------------------------+
| CW301_AVR     | Multi-Target Board, AVR Target        |
+-------------------------------------------------------+
| CW303         | XMEGA Target (CWLite), Also works     |
|               | for CW308T-XMEGA                      |
+-------------------------------------------------------+
| CW304         | ATMega328P (NOTDUINO), Also works     |
|               | for CW308T-AVR                        |
+-------------------------------------------------------+
| CW308_MEGARF  | ATMega2564RFR2 Target for CW308T      |
+-------------------------------------------------------+
+=======================================================+
+ ARM Cortex-M Targets (Generic)                        |
+=======================================================+
+-------------------------------------------------------+
| CWLITEARM     | CW-Lite Arm (Alias for CW308_STM32F3) |
+-------------------------------------------------------+
| CWNANO        | CW-Lite Nano (STM32F0_NANO)           |
+-------------------------------------------------------+
| CW308_STM32F0 | CW308T-STM32F0 (ST Micro STM32F0)     |
+-------------------------------------------------------+
| CW308_STM32F1 | CW308T-STM32F0 (ST Micro STM32F1)     |
+-------------------------------------------------------+
| CW308_STM32F2 | CW308T-STM32F2 (ST Micro STM32F2)     |
+-------------------------------------------------------+
| CW308_STM32F3 | CW308T-STM32F3 (ST Micro STM32F3)     |
+-------------------------------------------------------+
| CW308_STM32F4 | CW308T-STM32F4 (ST Micro STM32F405)   |
+-------------------------------------------------------+
+=======================================================+
+ ARM Cortex-M Targets (Support CRYPTO_TARGET=HWAES)    |
+=======================================================+
+-------------------------------------------------------+
| CW308_CC2538  | CW308T-CC2538 (TI CC2538)             |
+-------------------------------------------------------+
| CW308_        | CW308T-EFM32GG11                      |
|   EFM32GG11   | (Silicon Labs Giant Gecko)            |
+-------------------------------------------------------+
| CW308_        | CW-Lite EFM32TG11B                    |
|   EFM32TG11B  | (Silicon Labs Tiny Geko)              |
+-------------------------------------------------------+
| CW308_        | CW308T-EFR32MG21 (A version without   |
|   EFR32MG21A  |                   'secure vault')     |
+-------------------------------------------------------+
| CW308_        | CW308T-IMXRT1062 (iMX RT1062)         |
|   IMXRT1062   |   NXP "Cross-Over" Microcontroller    |
+-------------------------------------------------------+
| CW308_K24F    | CW308T-K24F (NXP Kinetis K24F)        |
+-------------------------------------------------------+
| CW308_K82F    | CW308T-K82F (NXP Kinetis K82F)        |
+-------------------------------------------------------+
| CW308_LPC55S6X| CW308T-LPC55S69 (NXP LPC55S69)        |
+-------------------------------------------------------+
| CW308_NRF52   | CW308T-NRF52840 (Nordic Semi)         |
+-------------------------------------------------------+
| CW308_PSOC62  | CW308T-PSOC62 (Cypress PSOC 62)       |
+-------------------------------------------------------+
| CW308_SAM4L   | CW308T-SAM4L (Atmel SAM4L)            |
+-------------------------------------------------------+
| CW308_SAML11  | CW-Lite SAML11 (Atmel SAML11)         |
+-------------------------------------------------------+
| CW308_STM32F2 | CW308T-STM32F2HWC (ST Micro STM32F215)|
+-------------------------------------------------------+
| CW308_STM32F4 | CW308T-STM32F4HWC (ST Micro STM32F415)|
+-------------------------------------------------------+
| CW308_STM32L4 | CW308T-STM32L4 (ST Micro STM32L443)   |
+-------------------------------------------------------+
| CW308_STM32L5 | CW308T-STM32L5HWC (ST Micro STM32L562)|
+-------------------------------------------------------+
+=======================================================+
+ Other 32-bit Architecture                             |
+=======================================================+
+-------------------------------------------------------+
| CW308_AURIX   | CW-Lite AURIX (Infineon TC233A)       |
+-------------------------------------------------------+
| CW308_FE310   | CW308T-FE310-G002 (RISC-V)            |
+-------------------------------------------------------+
| CW308_        | CW308T-MPC5676R (NXP MPC5676R)        |
|   MPC5676R    |                                       |
+---------------|---------------------------------------+

Options to define platform:
(1) Run make with PLATFORM specified as follows:
make PLATFORM=CW304

(2) Save a file called Makefile.platform with contents:
PLATFORM=CW304
.  Stop.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
C:\Users\moromugi\AppData\Local\Temp/ipykernel_20012/3058607573.py in <module>
----> 1 get_ipython().run_cell_magic('bash', '', "cd ../hardware/victims/firmware/simpleserial-base/\nmake PLATFORM= CRYPTO_TARGET='CWNANO'\n")

~\WPy64-3771\python-3.7.7.amd64\lib\site-packages\IPython\core\interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2401             with self.builtin_trap:
   2402                 args = (magic_arg_s, cell)
-> 2403                 result = fn(*args, **kwargs)
   2404             return result
   2405 

~\WPy64-3771\python-3.7.7.amd64\lib\site-packages\IPython\core\magics\script.py in named_script_magic(line, cell)
    140             else:
    141                 line = script
--> 142             return self.shebang(line, cell)
    143 
    144         # write a basic docstring:

~\WPy64-3771\python-3.7.7.amd64\lib\site-packages\decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~\WPy64-3771\python-3.7.7.amd64\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~\WPy64-3771\python-3.7.7.amd64\lib\site-packages\IPython\core\magics\script.py in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b"cd ../hardware/victims/firmware/simpleserial-base/\nmake PLATFORM= CRYPTO_TARGET='CWNANO'\n"' returned non-zero exit status 2.

**Comment by alex-dewar** [comment]
You need to set platform to your target (CWNANO). crypto_target allows you to select different crypto libraries to use (TINYAES, MBEDTLS, etc)
