### ISSUE TITLE
ERROR: No matching distribution found for chipwhisperer==random

### ISSUE THREAD

**Issue by mprt** [newaetech/chipwhisperer#378]
Looks like your "version-check" doesn't work the way you intended...
I think, pip can't handle the "==random".
I'm running pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9).

```
In [2]: cw.check_for_updates()
WARNING:ChipWhisperer Other:ChipWhisperer update available! See https://chipwhisperer.readthedocs.io/en/latest/installing.html for updating instructions

Out[2]: "stderr='ERROR:Couldnotfindaversionthatsatisfiestherequirementchipwhisperer==random\\nERROR:Nomatchingdistributionfoundforchipwhisperer==random\\n'"
```

https://github.com/newaetech/chipwhisperer/blob/7b9a62de088b0c1e3509f1db1936cba07fc8fee6/software/chipwhisperer/__init__.py#L46

**Comment by alex-dewar** [comment]
Looks like this is caused by using an old version of pip. We now do a version check for pip to make sure this works: a79b8dce020863b541244b1c811f7d28f36cb628
