### ISSUE TITLE
Capture: I/O Decoder trigger stays after switching Pro to Lite

### ISSUE THREAD

**Issue by gregdeon** [newaetech/chipwhisperer#38]
When a CW-Pro is connected, the I/O Decoder trigger module appears in the settings. It sticks around after we plug in a CW-Lite instead, and the Lite doesn't understand these settings, causing all kinds of USB errors. This module should vanish when a Lite is connected.

**Comment by alex-dewar** [comment]
I think this is a GUI only issue, so closing
