### ISSUE TITLE
PCB layout for the 32-bit ChipWhisperer-Lite (STM32F303)? 

### ISSUE THREAD

**Issue by F17** [newaetech/chipwhisperer#388]
Hello, could you please provide a pcb layout for 32bit CW Lite (STM32F303)? 
The repository only contains schematic and pcb layout (in Eagle) with ATXMEGA128A4U victim.

**Comment by alex-dewar** [comment]
You can find the schematic for the target side of the board on our hardware docs website at: https://rtfm.newae.com/Targets/Images/cw303-arm.png
