### ISSUE TITLE
Glitch output with very low voltage level

### ISSUE THREAD

**Issue by itewqq** [newaetech/chipwhisperer#414]
Hi there,

I was trying to use Chipwhisperer-Lite and ChipSHOUTER to work together, but found that Chipwhisperer could not drive the latter's hardware trigger.

Then I connected the glitch output of Chipwhisperer to the oscilloscope and found that **it can only output a very low voltage (0.4V)** at a time, is this normal? How can I get it to work properly?

![image](https://user-images.githubusercontent.com/30570177/179215938-e4e96f6f-371f-4831-9576-c99442a7e4b5.png)

For the hardware setup, I just plug the glitch output to a picoscope:

![~} LN~P~K0@315W9E63CBX3](https://user-images.githubusercontent.com/30570177/179216204-e4137f8f-0f74-4b3c-acef-ae64c93cf264.jpg)

**Comment by colinoflynn** [comment]
Hi @itewqq - the gltich output is actually one of two MOSFETs on the output you are activating, so there is no high drive. If you want to generate a logic-level signal, you'll have to route it to HS2:

```
scope.glitch.hs2 = "glitch"
```

However - you often want to use HS2 for clock & not glitch. This can be done using a pull-up on the glitch output & enabling the `glitch_lp` MOSFET.

But if using ChipSHOUTER, you don't need any external hardware as you can configured it to be active-low on trigger input, and it by default has a pull-up to prevent the input from floating. To do this, two configurations needed:

On ChipWhisperer:
```
scope.glitch.output = "enable_only"
scope.io.glitch_lp = True
```

On ChipSHOUTER:
```
set hwtrig_term 0
set hwtrig_mode 0
```
Note you might want to save those as new defaults with `write_nvm`, otherwise they need to be reconfigured on ever reboot of ChipSHOUTER.

![image](https://user-images.githubusercontent.com/6100154/179229132-77022ad5-fc72-48fe-a70a-e79fe4e47ba4.png)

This is described in more detail on Page 26 of the [ChipSHOUTER User Manual](https://media.newae.com/manuals/ChipSHOUTER_PRESS_1.4.pdf) (PDF warning).

Hope this helps! It's a little non-obvious about what the glitch output is, easy documentation is always lagging. Let us know if that works ok + makes sense.

**Comment by itewqq** [comment]
Thanks for the explanation! 

> This is described in more detail on Page 26 of the [ChipSHOUTER User Manual](https://media.newae.com/manuals/ChipSHOUTER_PRESS_1.4.pdf) (PDF warning).

Actually I've tried to connect ChipWhiperer and ChipSHOUTER the same way as described in the User Manual, but when I use `scope.glitch.manual_trigger()` in ChipWhisperer nothing happends. Besides the ChipSHOUTER may crash after this.

> On ChipWhisperer:
> 
> scope.glitch.output = "enable_only"
> scope.io.glitch_lp = True
> On ChipSHOUTER:
> 
> set hwtrig_term 0
> set hwtrig_mode 0

and the configuration I've adopted is exactly same here.

**Comment by itewqq** [comment]
Also, when I try to use `scope.glitch.hs2`, there is an error:

```
In [3]: scope.glitch.hs2 = "glitch"
(ChipWhisperer Other ERROR|File util.py:362) Setting unknown attribute hs2 in <class 'chipwhisperer.capture.scopes.cwhardware.ChipWhispererGlitch.GlitchSettings'>

```

**Comment by itewqq** [comment]
Ok now I'm not able to connect chipwhisperer :sweat_smile:

**Comment by itewqq** [comment]
The current version my test code is:

```python
from chipshouter import ChipSHOUTER
import chipwhisperer as cw
import time

CS_COM = "/dev/ttyUSB0"
cs = ChipSHOUTER(CS_COM)
cs.hwtrig_term = 0
cs.hwtrig_mode = 0

scope = cw.scope()
scope

scope.io.glitch_lp = True
scope.io.glitch_hp = False
scope.glitch.output = 'enable_only'
scope.glitch.repeat = 3
scope.glitch.trigger_src = 'manual'

print(scope.glitch)
cs.armed = True
time.sleep(1)

scope.arm()
scope.glitch.manual_trigger()
```

BTW I can trigger the ChipSHOUTER with a raspberry pi 3b+ using gpio pin.

The hardware connection is just same as you mentioned:

![image](https://user-images.githubusercontent.com/30570177/179460477-230b7823-df78-4e37-8305-70b49e2e4530.png)

**Comment by alex-dewar** [comment]
I'll try replicating this on a ChipShouter. Have you tried measuring the trigger pin on the ChipShouter to see if the pullup is actually pulling the IO line up? I'm fairly sure that's the issue.

For clock glitching, it should be `scope.io.hs2 = "glitch"` instead of `scope.glitch.hs2 = "glitch"`. Also you should set `scope.glitch.clk_src = "clkgen"` to setup the glitch clock.

Also sorry for the version check, I've modified it so it should only check once, then timeout (default is 5 times).

**Comment by colinoflynn** [comment]
Oops sorry forgot to respond as well - I'd double-check the glitch clock is running too. You can issue a reset to the glitch clock DCM, it may be the glitch clock isn't running. I'd crank the `repeat` way up as a first test too (set it to 500 or something).

**Comment by itewqq** [comment]
>Have you tried measuring the trigger pin on the ChipShouter to see if the pullup is actually pulling the IO line up? I'm fairly sure that's the issue.

Yes, the trigger pin of ChipShouter is actually up.

>For clock glitching, it should be scope.io.hs2 = "glitch" instead of scope.glitch.hs2 = "glitch". Also you should set scope.glitch.clk_src = "clkgen" to setup the glitch clock.

I've set the scope.glitch.clk_src = "clkgen" but it didn't work, too. My test code:

```python
from chipshouter import ChipSHOUTER
import chipwhisperer as cw

CS_COM = "/dev/ttyUSB1"

cs = ChipSHOUTER(CS_COM)
scope = cw.scope()

cs.hwtrig_term = 0
cs.hwtrig_mode = 0

scope.io.glitch_lp = True
scope.io.glitch_hp = False
scope.glitch.clk_src = "clkgen" # set glitch input clock
scope.glitch.output = 'enable_only'
scope.glitch.repeat = 500
scope.glitch.trigger_src = 'manual'

cs.armed = True
scope.arm()
scope.glitch.manual_trigger()
```

Also, when I first connect the ChipWhisperer and ChipSHOUTER, then run the code, ChipSHOUTER will alert with a beep and the lights are:

![image](https://user-images.githubusercontent.com/30570177/179901407-1e98c320-d732-4b04-95cf-229a63ac75ec.png)

And the fault light won't go off until I disconnect the CW and CS.

**Comment by itewqq** [comment]
I also tried the `hs2` output pin, it's not working too.

My test code:
```python
import chipwhisperer as cw
import time

scope = cw.scope()
scope

scope.glitch.output = 'enable_only'
scope.glitch.clk_src = "clkgen"
scope.io.hs2 = "glitch"
scope.glitch.repeat = 500
scope.glitch.trigger_src = 'manual'

scope.arm()
scope.glitch.manual_trigger()
```
Output of `scope`:

```
cwlite Device
sn         = 53313120313436373130303130333032
fw_version = 
    major = 0
    minor = 62
    debug = 0
gain = 
    mode = low
    gain = 0
    db   = 5.5
adc = 
    state          = False
    basic_mode     = low
    timeout        = 2
    offset         = 0
    presamples     = 0
    samples        = 24400
    decimate       = 1
    trig_count     = 902539329
    fifo_fill_mode = normal
clock = 
    adc_src       = clkgen_x1
    adc_phase     = 0
    adc_freq      = 96000000
    adc_rate      = 96000000.0
    adc_locked    = True
    freq_ctr      = 0
    freq_ctr_src  = extclk
    clkgen_src    = system
    extclk_freq   = 10000000
    clkgen_mul    = 2
    clkgen_div    = 1
    clkgen_freq   = 192000000.0
    clkgen_locked = True
trigger = 
    triggers = tio4
    module   = basic
io = 
    tio1         = serial_tx
    tio2         = serial_rx
    tio3         = high_z
    tio4         = high_z
    pdid         = high_z
    pdic         = high_z
    nrst         = high_z
    glitch_hp    = False
    glitch_lp    = False
    extclk_src   = hs1
    hs2          = glitch
    target_pwr   = True
    tio_states   = (1, 0, 0, 0)
    cdc_settings = bytearray(b'\x01\x00\x00\x00')
glitch = 
    clk_src     = clkgen
    width       = 10.15625
    width_fine  = 0
    offset      = 10.15625
    offset_fine = 0
    trigger_src = manual
    arm_timing  = after_scope
    ext_offset  = 0
    repeat      = 500
    output      = enable_only
```

My hardware connection:

![image](https://user-images.githubusercontent.com/30570177/179905983-97b76de5-68fa-4ac7-943a-caa72d2e3139.png)

**Comment by alex-dewar** [comment]
Can you try calling `scope.default_setup()` as well? That should reset all the clocks and make sure the DCMs are locked

**Comment by itewqq** [comment]
>Can you try calling scope.default_setup() as well? That should reset all the clocks and make sure the DCMs are locked

It's working perfectly after `scope.default_setup() `, thanks very much!!!

**Comment by itewqq** [comment]
Well it happened AGAIN, after I update the firmware from0.62 to 0.64 today:

![image](https://github.com/newaetech/chipwhisperer/assets/30570177/f9d22e91-0c60-4747-828d-b26a542f06ff)

The output of the Glitch signal is too small to trigger the ChipSHOUTER, just as the above disccued issue.
But this time the `scope.default_setup()` trick does not work...

Test code:
```python
import chipwhisperer as cw

# ChipWhisperer
scope = cw.scope()
scope.default_setup()

# ChipWhisperer trigger settings

scope.io.glitch_lp = True
scope.io.glitch_hp = False
scope.glitch.clk_src = "clkgen" # set glitch input clock
scope.glitch.output = 'enable_only'
scope.glitch.repeat = 100
scope.glitch.trigger_src = 'manual'

# Manully trigger it
scope.arm()
```

Env:
```
cwlite Device
sn         = 53313120313436373130303130333032
fw_version = 
    major = 0
    minor = 64
    debug = 0
gain = 
    mode = high
    gain = 30
    db   = 24.8359375
adc = 
    state          = False
    basic_mode     = rising_edge
    timeout        = 2
    offset         = 0
    presamples     = 0
    samples        = 5000
    decimate       = 1
    trig_count     = 0
    fifo_fill_mode = normal
clock = 
    adc_src       = clkgen_x4
    adc_phase     = 0
    adc_freq      = 29538471
    adc_rate      = 29538471.0
    adc_locked    = True
    freq_ctr      = 0
    freq_ctr_src  = extclk
    clkgen_src    = system
    extclk_freq   = 10000000
    clkgen_mul    = 2
    clkgen_div    = 26
    clkgen_freq   = 7384615.384615385
    clkgen_locked = True
trigger = 
    triggers = tio4
    module   = basic
io = 
    tio1         = serial_rx
    tio2         = serial_tx
    tio3         = high_z
    tio4         = high_z
    pdid         = high_z
    pdic         = high_z
    nrst         = high_z
    glitch_hp    = False
    glitch_lp    = True
    extclk_src   = hs1
    hs2          = clkgen
    target_pwr   = True
    tio_states   = (0, 1, 0, 0)
    cdc_settings = bytearray(b'\x00\x00\x00\x00')
glitch = 
    clk_src     = clkgen
    width       = 10.15625
    width_fine  = 0
    offset      = 10.15625
    offset_fine = 0
    trigger_src = manual
    arm_timing  = after_scope
    ext_offset  = 0
    repeat      = 100
    output      = enable_only
```

Python package `chipwhisperer==5.7.0`.

**Comment by alex-dewar** [comment]
It looks like you're trying to do the same thing you were doing originally, which is using the glitch port. It's just an open drain transistor, so it can't do anything but pull voltages low. You need to use the HS2 pin with `scope.io.hs2 = "glitch"`

**Comment by itewqq** [comment]
@alex-dewar Thanks for the quick response!

I'm using the glitch SMA output, following the ChipShouter manul:

![image](https://github.com/newaetech/chipwhisperer/assets/30570177/4a4b5c2e-89fb-48bd-82f9-4db2d4acfa78)

And it cannot trigger the ChipShouter so I connect the glitch SMA output to the oscilloscope to check it out.

>You need to use the HS2 pin with scope.io.hs2 = "glitch"

Do you mean that I should use the HS2 pin instead of the SMA connector? Or just write this in the code but still use the SMA output?

**Comment by alex-dewar** [comment]
You can use the ChipWhisperer and ChipShouter as above, but you need to make sure the latter has its internal pullup resistor enabled by setting the ChipShouter's `hwtrig_term = 0` and `hwtrig_mode = 0`.

**Comment by itewqq** [comment]
@alex-dewar Of course I did that, but seems not working.

I'm off my lab and will check it serveral hours later. 

BTW I'm always confused about the operation order. Currentyly my setting process is like:

1. Connect CW and CS in power off state.
2. Power on the CS and set `cs.hwtrig_term = 0`, `cs.hwtrig_mode = 0`
3. Power on the CW by connecting to computer and make a `scope.default_setup()`. 
4. Then setup other CW options like glitch_lp/glitch_hp.
5. Start my dedicate work hereafter.

Sometimes the CS won't be happy with this and beeps for 1~2 seconds. I wonder what's the correct way to boot everything up. Would be very appreciate if you can give some advice.

**Comment by itewqq** [comment]
@alex-dewar It still cannot work with chipshouter, my test code:

```python
import sys
import time
import os
import numpy as np
from tqdm.notebook import tqdm
import serial
import matplotlib.pyplot as plt


from chipshouter import ChipSHOUTER
import chipwhisperer as cw

CS_COM = "/dev/ttyUSB0"

# ChipSHOUTERimport serial
cs = ChipSHOUTER(CS_COM)
# ChipWhispererscope.arm()
scope = cw.scope()
# Target board
target_ser = None

# reset default

scope.default_setup()

# ChipWhisperer trigger settings
scope.io.glitch_lp = True
scope.io.glitch_hp = False

scope.clock.clkgen_src = 'system' 
scope.clock.clkgen_freq = 200e6          # Main ChipWhisperer clock
# scope.clock.adc_mul = 0
scope.trigger.triggers = 'tio4'          # Trigger on a rising edge of TIO4 (connected to DIO6)
scope.adc.basic_mode = 'rising_edge'     # Rising edge for trigger
scope.io.target_pwr = True

scope.glitch.clk_src = "clkgen" # set glitch input clock
#scope.clock.pll.update_fpga_vco(600e6)
scope.glitch.output = 'enable_only'
scope.glitch.trigger_src = 'ext_single' # external single trigger
scope.glitch.ext_offset = 300            # Glitch offset from the external trigger (in cycles of the main CW clock)
scope.glitch.repeat = 100 # You might want to try different values for this parameter

# print(scope)

time.sleep(2)

# ChipSHOUTER trigger settings
cs.hwtrig_term = 0
cs.hwtrig_mode = 0
cs.voltage = 500
cs.pulse.width = 160
# print(cs)

# trigger test
cs.armed = True
time.sleep(2)
scope.arm()
time.sleep(2)
cs.armed = False
```

Besides, there is also a red led keep showing in the CW board after running the code above:

![image](https://github.com/newaetech/chipwhisperer/assets/30570177/03242c82-1b5b-42f1-a874-f9cd82b95d6e)

**Comment by itewqq** [comment]
Update: I change the `scope.clock.clkgen_freq` from 200e6 to around 160e6 and it works now.

However, the manual said the max freq for CW lite is 200MHz right? https://rtfm.newae.com/Capture/ChipWhisperer-Lite/#:~:text=Clock%20Generation%20Range

**Comment by jpcrypt** [comment]
While CW-lite can generate a 200 MHz clock, its FPGA may not function properly at such a high clock frequency, i.e. it may not trigger and/or generate the output glitch pulse correctly (or at all).

**Comment by alex-dewar** [comment]
You could try locking the DCMs a couple extra times via `scope.clock.reset_dcms()`, checking with `scope.clock.clkgen_locked`, but your frequency generation range is something that'll vary from FPGA to FPGA. I'd recommend just using a lower clock frequency.

**Comment by itewqq** [comment]
Thanks @alex-dewar @jpcrypt
