### ISSUE TITLE
Diagram Figure Mismatch for Glitch

### ISSUE THREAD

**Issue by alex-dewar** [newaetech/chipwhisperer#420]
https://forum.newae.com/t/fault101-fault-1-1-circuit-or-timing-diagram-error-on-4th-figure/3509/2

**Comment by colinoflynn** [comment]
This is familiar from somewhere else - may be the error is the circuit diagram. Will check if there was an updated version about that.

**Comment by colinoflynn** [comment]
![image](https://user-images.githubusercontent.com/6100154/192840478-2ee99d9c-a7b5-468b-91d4-6dec08b0d84b.png)

**Comment by colinoflynn** [comment]
This was version in HHH - I think it's just the NOT input was incorrect on which was phase shift 1/2. But need to check if it still matches hardware, this diagram didn't need to match CW was just to demonstrate how a glitcher could be made.

**Comment by alex-dewar** [comment]
Closing, as this has been fixed in the fault101 notebooks
