### ISSUE TITLE
Chip not connecting on Mac

### ISSUE THREAD

**Issue by rdaw6** [newaetech/chipwhisperer#423]
I'm trying to use a ChipWhisperer NANO on macOS Big Sur 11.6.8, and am getting the following issue:

<img width="1006" alt="Screen Shot 2022-10-31 at 10 13 39 AM" src="https://user-images.githubusercontent.com/113135441/199028676-013d78ce-af9b-450f-93f0-f22a4e15aa07.png">

The chip is connected via a thunderbolt 3 port with a USB C to USB adapter, and the USB light on the chip is lit up, so I assume this verifies it is connected.

I know there is a little less documentation on using chipwhisperer with Mac, so I tried using windows through bootcamp, but still received the same error.

**Comment by alex-dewar** [comment]
Hi,

Does the green USB LED blink, or does it stay lit? If it's the latter, it might be related to https://github.com/newaetech/chipwhisperer/issues/237.

If the LED does blink, can you confirm that you have libusb  installed, then run `system_profiler SPUSBDataType` in a terminal?

**Comment by alex-dewar** [comment]
Hi,

Any update on this?

**Comment by alex-dewar** [comment]
Closing, as there's been no update for a while.

**Comment by unixb0y** [comment]
I have the same issue with ChipWhisperer Pro (CW1200) and no matter which USB-C to USB-A adapter I use.
I think it's a software issue, since the CW shows up in System Information and in `system_profiler` without issues.

MacBook Pro with M2 Pro, on macOS 13.6
