### ISSUE TITLE
Scope Armored led issue

### ISSUE THREAD

**Issue by M0nteCarl0** [newaetech/chipwhisperer#437]
Dear, when i try meausre with  scope setup:

scope.adc.basic_mode = 'Low'
scope.gain.db = 1

The CW armored LED don't blinky after every captured trace.
But when I measure with  scope setup:

scope.adc.basic_mode = 'High '
scope.gain.db = 1

Armored LED blinky is normal.
FW version CW Is {'major': 1, 'minor': 30, 'debug': 0} and CW API version is 5.5.1

**Comment by jpcrypt** [comment]
The "armored" LED is turned on when `scope.arm()` is called (e.g. by `cw.capture_trace()`); it's turned off when the capture starts.

I'm assuming that in both cases, your trigger input is low when `scope.arm()` is called. If `scope.adc.basic_mode = 'low'`, then the capture condition is met as soon as you arm the scope, and so the LED is turned on and then immediately back off, so you can't see it.

In "normal" ChipWhisperer use (e.g. if you follow our Jupyter courses or demos), the scope is armed, then a message is sent to the target which causes a trigger for the capture; this sequence results in a brief moment where the scope is armed but not capturing, and so you see the armed LED turn on briefly.
