### ISSUE TITLE
Update Installing_ChipWhisperer

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#44]
Hi,

I noticed the installing from git adds a second repository (openacd) under the current directory. There is nothing wrong with this but given the main git repository already contains a .gitsubmodule file it is enough
to say 

> git submodule init
> git submodule update

https://wiki.newae.com/Installing_ChipWhisperer

**Comment by gregdeon** [comment]
Good idea - that's a bit cleaner. I'll see if we can update the tutorial to use this instead.

**Comment by gregdeon** [comment]
Done. @colinoflynn says that this page was in a weird hybrid state - originally OpenADC wasn't a submodule, and when it changed the documentation didn't follow it.
