### ISSUE TITLE
CW Husky triggers on UART only once

### ISSUE THREAD

**Issue by nikolaychokoev** [newaetech/chipwhisperer#440]
My configuration is 

`
scope.clock.clkgen_src = "system"
scope.clock.adc_mul = 1
scope.clock.clkgen_freq = 100e6

scope.io.tio1 = "serial_rx"
scope.io.tio2 = "serial_tx"
scope.io.glitch_lp = True
scope.io.hs2 = "clkgen"

scope.glitch.enabled = True
scope.glitch.clk_src = 'pll'
scope.clock.pll.update_fpga_vco(600e6)
scope.glitch.output = 'glitch_only' #"enable_only" #"clock_xor"
scope.glitch.trigger_src = "ext_continuous" #"ext_single" #'manual' #
scope.glitch.repeat = 100
assert scope.glitch.mmcm_locked
scope.glitch.width = 40

scope.trigger.module = 'UART'
scope.trigger.triggers = 'tio2' # serial_tx
scope.UARTTrigger.enabled = True
scope.UARTTrigger.baud = 115200
scope.UARTTrigger.set_pattern_match(0, [0, 0, 0, 0, 0, 0, 0, 0xEE], [0, 0, 0, 0, 0, 0, 0, 255]) 
scope.UARTTrigger.trigger_source = 0
scope.UARTTrigger.rules_enabled = [0]
scope.io.glitch_trig_mcx = 'trigger'
`

I see only one glitch on the first occurrence of **_0xEE_** byte on the UART TX pin.

I expect to see a glitch on "**Trigger/Glitch Out**" every time I have **_0xEE_** on the UART TX as I have set `scope.glitch.trigger_src = "ext_continuous"`.

**Comment by jpcrypt** [comment]
As noted in the [Husky triggers notebook](https://github.com/newaetech/chipwhisperer-jupyter/blob/master/demos/husky/02%20-%20Husky%20Triggers.ipynb):

> The UART trigger module supports issuing multiple triggers: *up to* `scope.UARTTrigger.capture.max_triggers` can be issued. Once this limit is reached, no more triggers are issued until the scope is re-armed.
