### ISSUE TITLE
aes_sbox_lut.v file?

### ISSUE THREAD

**Issue by aledolme** [newaetech/chipwhisperer#449]
Hi!
I recently bought the CW305 target board. I would like to program the FPGA. I am trying to use the example in:
hardware/victims/cw305_artixtarget/fpga/vivado_examples/aes128_verilog
opening directly the project file for VIVADO (.xpr file). However, it could not find aes_sbox_lut.v file, which should be in
../../../cryptosrc/aes_newae/aes_sbox_lut.v

Where can I find it?
The same hold true for hardware/victims/cw305_artixtarget/fpga/vivado_examples/aes128_pipelined project, while hardware/victims/cw305_artixtarget/fpga/vivado_examples/ecc_p256_pmul is working. 

Thanks you, 
Alessandra

**Comment by jpcrypt** [comment]
Thank you for pointing this out! I've added the missing file.
