### ISSUE TITLE
https://wiki.newae.com/Installing_ChipWhisperer 

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#45]
Hi,

Following https://wiki.newae.com/Installing_ChipWhisperer I tried the quick tests.

These currently fail because they can not find the .hex files that are located in the tests directory.

WARNING:Could not execute method run in script class Capture: 'IOError:[Errno 2] No such file or directory: 'simpleserial-des-xmega.hex''

I fudged a solution here
https://gist.github.com/x8-999-github/61d1fe3e217a9954b974313fe9cfe437

**Comment by x8-999-github** [comment]
Added #46 (if you like the code) else -> throw it away :p

**Comment by gregdeon** [comment]
Looks like Colin merged this in https://github.com/newaetech/chipwhisperer/pull/46. Thanks!
