### ISSUE TITLE
SAM4S Target Trace Divergence

### ISSUE THREAD

**Issue by alex-dewar** [newaetech/chipwhisperer#456]
The SAM4S seems to sometimes generate traces that look very different for a small portion of the AES algorithm. It's unclear if this is caused by the data that's being processed or some other reason. This doesn't seem to happen with the STM32F3 target with Husky.

![image](https://github.com/newaetech/chipwhisperer/assets/35226274/f2e64067-3d18-4836-8fbe-d8aeb04dbc47)

**Comment by alex-dewar** [comment]
Was caused by loop optimizations in the SAM4S. Disabling this fixes the issue. Will close when a fix is pushed

**Comment by alex-dewar** [comment]
Fixed by 8b46fbd69867c1885066e4176e24f13ee6698db0

**Comment by colinoflynn** [comment]
Nice catch! Had seen that for a while and never investigated, interesting there is still some flash/cache stuff hidden away a bit. For reference for anyone else, this is the SAM4S feature:
<img width="572" alt="image" src="https://github.com/newaetech/chipwhisperer/assets/6100154/4c4bb414-67a7-4a5a-9d76-f04c7e0665da">
