### ISSUE TITLE
USART.read() returns too much data in case of timeout

### ISSUE THREAD

**Issue by jan2642** [newaetech/chipwhisperer#463]
When using USART.read() with a timeout and the timeout expires before the requested amount of bytes has been received, the function will still return an array with the requested amount of bytes but they're all 0x00.

Example where no bytes are coming in:
```python
>>> a = serial.read(5, timeout = 1000)
>>> print(a)
[0, 0, 0, 0, 0]
```

This bug was introduced in https://github.com/newaetech/chipwhisperer/commit/bf754afa09bd93bba4ad31da2bcd0d4f87001615 when reducing memory copies. Before that commit the result is:
```python
>>> a = serial.read(5, timeout = 1000)
>>> print(a)
[]
```
The very easy fix is to change this line:
https://github.com/newaetech/chipwhisperer/blob/a891ded296bf4eaada2b90e795c0bd1d02e97cf9/software/chipwhisperer/hardware/naeusb/serial.py#L234
into:
```python
        return resp[:pos]
```
This way only the received bytes will be returned. Unfortunately it seems that that statement will always make a copy, even if `pos == len(resp)`, exactly what https://github.com/newaetech/chipwhisperer/commit/bf754afa09bd93bba4ad31da2bcd0d4f87001615 tried to reduce.

Another option which avoids the memcpy could be this:
```python
        if dlen == 0:
            return resp
        else:
            return resp[:pos]
```

**Comment by alex-dewar** [comment]
Thanks for the report, should be fixed now
