### ISSUE TITLE
GUI for Chipwhisper

### ISSUE THREAD

**Issue by hafizuriu** [newaetech/chipwhisperer#471]
Hi, I am a new chipwhisperer user. Is there any GUI to visualize the data?
Is there any tutorial for the chipwhisperer level 2 kit?

Thanks in advance.

**Comment by jpcrypt** [comment]
There is no GUI, however data visualization is possible in Jupyter; we show how in our [chipwhisperer-jupyter repository](https://github.com/newaetech/chipwhisperer-jupyter/).
This is also where you will find a large selection of tutorials, most of which can be run on your level 2 kit.
