### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by gmgunderground** [newaetech/chipwhisperer#498]
Is there another repository or is right taht there arent updates from Jenuary 2023?

**Comment by colinoflynn** [comment]
We hadn't tagged a release in some time (we have a [5.7.1](https://github.com/newaetech/chipwhisperer/blob/develop/CHANGES.txt) in CHANGES.txt) mentioned that wasn't a release on GH), but there have been a lot of updates as you can see in the [commit tree](https://github.com/newaetech/chipwhisperer/commits/develop/).

The actual releases have a Windows installer built that is slower. Normally we recommend going to HEAD to get the latest.

Note a lot of the interesting updates are in the [chipwhisperer-jupyter](https://github.com/newaetech/chipwhisperer-jupyter)repo too (which gets pulled in).
