### ISSUE TITLE
Chipwhisperer CW305 - 100T

### ISSUE THREAD

**Issue by alimousios98x** [newaetech/chipwhisperer#505]
Hello i am using Chipwhisperer CW305 - 100T for a project i am trying to create. Where can i find the xdc constraints files related to its fpga part (xc7a100tfgg676-2).

**Comment by jpcrypt** [comment]
Here is the [.xdc file](https://github.com/newaetech/chipwhisperer/blob/develop/firmware/fpgas/aes/vivado/cw305.xdc) for our [example AES project](https://github.com/newaetech/chipwhisperer/blob/develop/firmware/fpgas/aes/vivado/cw305_aes.xpr).
More info about this project is [here](https://github.com/newaetech/chipwhisperer/tree/develop/firmware/fpgas/aes).
