### ISSUE TITLE
Cryptic error messages: NoneType has no attribute "InWaiting"

### ISSUE THREAD

**Issue by gregdeon** [newaetech/chipwhisperer#53]
When the target is disconnected, trying to Capture 1 gives a strange error message. This should really say something like "No target connected - to capture traces, first connect to target"

**Comment by gregdeon** [comment]
I can't reproduce this. I think that an exception must have set the target to None making this bug appear, but I can't figure out where. I'll leave this issue open for now.

**Comment by FranzHeubach** [comment]
Understandable error is now raised when target or scope is None. Fixed in 8a710a27fba1a9067130948edc8c1ddde90db2ab
