### ISSUE TITLE
Glitch Explorer serial response wait in Simpleserial timeout to short

### ISSUE THREAD

**Issue by MaikStohn** [newaetech/chipwhisperer#7]
I try to glitch a traget based on Simpleserial and always got empty responses in glitch monitor however terminal showed a lot of data coming back.

After adding a timeout for the serial read everything worked fine:

```
        if fmt.startswith("$GLITCH$"):
            try:
                databytes = int(fmt.replace("$GLITCH$",""))
            except ValueError:
                databytes = 64

-            self.newInputData.emit(self.ser.read(databytes))
+            self.newInputData.emit(self.ser.read(databytes, timeout=1000))
            return None
```                    

This is not optimal (now it always takes 1 second for the trace to finish, regardless if the output arrives earlier) but it solved my problem.

Better would be to start the response read based on the trigger since my target needs some time to arrive at the trigger output and glitch point (between 500-700 msec).

**Comment by x8-999-github** [comment]
#161 fixed this issue
