### ISSUE TITLE
Finish removing autoscript

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#78]
In API 4.0.0 Autoscript is dead. Long live autoscript.

Now instead of making little weird automatic scripts, we will be using the __repr__ function to dump settings associated with all parameters. If the user sets stuff via the GUI, they can replicate this on the command line by just inspecting all the settings of an object, and setting applicable properties in their own code.

**Comment by FranzHeubach** [comment]
Going through older issues. This issue has largely been solved. Both target and scope and chipwhisperer can be inspected through the **repr** function printing all settings that can be changed.
