### ISSUE TITLE
CW308T-87C51 PCB design files are missing

### ISSUE THREAD

**Issue by d235j** [newaetech/chipwhisperer#83]
The wiki at https://wiki.newae.com/CW308T-87C51 has a link to https://github.com/newaetech/chipwhisperer/tree/master/hardware/victims/cw308_ufo_target/87c51

Unfortunately, this returns a 404. Can someone please upload? 😄

**Comment by colinoflynn** [comment]
Now in develop branch (wiki points here too) along with all firmware & PCB design source files.
