### ISSUE TITLE
Spammers on the forum

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#89]
Hello,

There are spammers on the forum that require some attention

**Comment by x8-999-github** [comment]
https://forum.newae.com/viewtopic.php?f=6&t=553 for example

**Comment by FranzHeubach** [comment]
Thank you for letting us know. We dealt with the spam we could find. I will leave this issue open so if anyone comes across any more spam you can leave a comment here, and we can deal with it.
