### ISSUE TITLE
Download CW Firmware Button Errors

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#9]
1. Connect to CW-Lite/CW1200
2. Open CW Firmware Preferences Window
3. Disconnect & then Reconnect to CW
4. Hit "Program FPGA"

Problem seems to be related to keeping wrong reference around, needs fixing.

**Comment by gregdeon** [comment]
This is now (relatively) fixed - every time the firmware GUI is opened, it reloads the firmware programmer object. This fixes a few related problems (CWLite appearing as default device type, failure when trying to program an unconnected device). See 8dbc0e6c105fc94cf2440a5aec11f05164226c39 for details.
