### ISSUE TITLE
inconsistent scope.io.glitch_lp

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#91]
![selection_112](https://user-images.githubusercontent.com/22741063/35094644-25cdf66c-fc46-11e7-9805-98c35d5f94fd.png)
Hi,

There is some inconsistent behaviour of the glitch_lp "setting" (4.x branch)

>>> scope.io.glitch_lp 
2
>>> scope.io.glitch_lp =1
>>> scope.io.glitch_lp 
2

The second problem that is related to that is that the "HS-Glitch Out Enable(Low Power)" does not get 
toggled when setting scope.io.glitch_lp  from the console

![selection_113](https://user-images.githubusercontent.com/22741063/35094677-43fe67de-fc46-11e7-8385-e7c20705c41e.png)

**Comment by FranzHeubach** [comment]
The ability to set the toggle option to True or False from the command line was fixed. The GUI still does not update but that might take some more research.

**Comment by alex-dewar** [comment]
New CW5 release with Jupyter notebook interface has removed old GUI problems, so closing this bug.
