### ISSUE TITLE
CANoodler information missing from wiki

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#94]
Hi,

On the strore a link to CANoodler is posted to the wiki but that leads to knowhere. If would be
nice to get more info /schematics on the CANoodler.

http://store.newae.com/stm32f3-target-for-cw308-automotive-bundle-w-canoodler/

Some info is actually posted here:
http://store.newae.com/canoodler/

**Comment by colinoflynn** [comment]
Will update - quick answer is link at https://github.com/newaetech/CANoodler has everything!

**Comment by colinoflynn** [comment]
Which reminds me to update STM32F wiki page with CAN details, crap. In progress...
